# Generated by Django 5.2.8 on 2025-11-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('INDOOR', 'Комнатные растения'), ('OUTDOOR', 'Садовые растения'), ('SUCCULENT', 'Суккуленты'), ('FLOWERING', 'Цветущие растения')], max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='plants/', verbose_name='Изображение')),
                ('care_instructions', models.TextField(verbose_name='Инструкции по уходу')),
                ('light_requirements', models.CharField(max_length=100, verbose_name='Требования к свету')),
                ('watering_needs', models.CharField(max_length=100, verbose_name='Полив')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
    ]
